version: "3.6"

services:

  consul_server:
    build:
      context: consul_server
      dockerfile: Dockerfile
    image: consul_server
    ports:
      - 8300:8300
      - 8301:8301
      - 8302:8302
      - 8400:8400
      - 8500:8500
    environment:
      - NODE=consul_server
      - PRIVATE_IP_ADDRESS=172.20.20.2
    networks:
      test:
        ipv4_address: 172.20.20.2

  load_balancer:
    image: fabiolb/fabio
    ports:
      - 9998:9998
      - 9999:9999
    command: -registry.consul.addr="172.20.20.2:8500"
    networks:
      test:
        ipv4_address: 172.20.20.100

  web_1:
    build:
      context: web
      dockerfile: Dockerfile
    image: web_consul
    ports:
      - 8081:80
    environment:
      - NODE=web_1
      - LOAD_BALANCER=172.20.20.100
      - PRIVATE_IP_ADDRESS=172.20.10.11
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - consul_server
      - load_balancer
    cap_add:
      - NET_ADMIN
    networks:
      test:
        ipv4_address: 172.20.10.11

  web_2:
    build:
      context: web
      dockerfile: Dockerfile
    image: web_consul
    ports:
      - 8082:80
    environment:
      - NODE=web_2
      - LOAD_BALANCER=172.20.20.100
      - PRIVATE_IP_ADDRESS=172.20.10.12
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - consul_server
      - load_balancer
    cap_add:
      - NET_ADMIN
    networks:
      test:
        ipv4_address: 172.20.10.12

networks:
  test:
#    driver: ipvlan
#    driver_opts:
#        parent: eth0
#    ipam:
#        config:
#            - 
#                subnet: 172.20.0.0/16
#                gateway: 172.20.0.1
    driver: bridge
    ipam:
        config:
            - subnet: 172.20.0.0/16       