---
- hosts: local
  become: yes
  become_user: root
  vars:
  webserver_message: "I am running to the finish line."
  tasks: 
  - name: Start Nginx
    apt: pkg=nginx state=present
  notify:
  - Ensure Nginx Is Started
  handlers:
  - name: Ensure Nginx Is Started
  service: name=nginx state=started
