version: "3.6"

services:

  tst_app:
    build:
      context: tst_app
      dockerfile: Dockerfile
    image: tst-app:1.0.0
    container_name: tst-app
    ports:
      - 81:80
    environment:
      - NODE=tst_srv
      - PRIVATE_IP_ADDRESS=172.10.0.11
#    networks:
#      tst_network:
#        ipv4_address: 172.10.0.11


  net_app:
    build:
      context: net_app
      dockerfile: Dockerfile
    image: net-app:0.1.0
    container_name: net-app
    ports:
      - 5000:5000
      - 5001:5001
            

#networks:
#  tst_network:
#    driver: bridge
#    ipam:
#     config:
#       - subnet: 172.10.0.0/24