apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nube
  namespace: test
  labels:
    app: nginx-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx-test
        image: "nginx:1.14.2"
        ports:
        - containerPort: 80