apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-d1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 20Gi
      
 